management:
  endpoint:
    chaosmonkey:
      enabled: false
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      level: 3
      latency-active: true

spring:
  config:
    active:
      on-profile: default
  cloud:
    kubernetes:
      enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: kubernetes
      on-cloud-platform: kubernetes
  cloud:
    kubernetes:
      enabled: true
      discovery:
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
        enabled: true
eureka:
  client:
    enabled: false
